#!/usr/bin/env bash
# Generates local secrets for SlotKeeper and writes them to .env (never committed).
# Requires: openssl, docker (for the BCrypt hash via htpasswd or an Alpine container).
# Usage: scripts/gen-secrets.sh [admin-password]

set -euo pipefail

ADMIN_PASSWORD="${1:-}"
if [ -z "$ADMIN_PASSWORD" ]; then
  echo "Enter the dashboard admin password:"
  read -rs ADMIN_PASSWORD
fi
if [ ${#ADMIN_PASSWORD} -lt 8 ]; then
  echo "Password must be at least 8 characters." >&2
  exit 1
fi

ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
  echo "Backing up existing $ENV_FILE to $ENV_FILE.bak"
  cp "$ENV_FILE" "$ENV_FILE.bak"
fi

gen_b64_key() {
  openssl rand -base64 32 | tr -d '\n'
}

gen_password() {
  openssl rand -hex 16
}

# BCrypt strength 12 hash via a throwaway Alpine httpd container (no host dependency).
bcrypt_hash() {
  local password="$1"
  if command -v htpasswd >/dev/null 2>&1; then
    htpasswd -bnBC 12 "" "$password" | tr -d ':\n' | sed 's/^//'
  elif command -v docker >/dev/null 2>&1; then
    docker run --rm httpd:alpine htpasswd -bnBC 12 "" "$password" | tr -d ':\n'
  else
    echo "Neither htpasswd nor docker found: cannot generate the BCrypt hash." >&2
    exit 1
  fi
}

ENCRYPTION_KEY=$(gen_b64_key)
PHONE_HMAC_KEY=$(gen_b64_key)
DB_MIGRATION_PASSWORD=$(gen_password)
DB_APP_PASSWORD=$(gen_password)
ADMIN_PASSWORD_HASH=$(bcrypt_hash "$ADMIN_PASSWORD")

cat > "$ENV_FILE" <<EOF
# Generated by scripts/gen-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Local only. Never commit this file.

SPRING_PROFILES_ACTIVE=dev
APP_BASE_URL=http://localhost:8080
FRONTEND_ORIGIN=http://localhost:5173

DB_URL=jdbc:postgresql://db:5432/slotkeeper
DB_MIGRATION_USER=slotkeeper_migrate
DB_MIGRATION_PASSWORD=$DB_MIGRATION_PASSWORD
DB_APP_USER=slotkeeper_app
DB_APP_PASSWORD=$DB_APP_PASSWORD

ADMIN_USERNAME=owner
ADMIN_PASSWORD_HASH=$ADMIN_PASSWORD_HASH

ENCRYPTION_KEY=$ENCRYPTION_KEY
PHONE_HMAC_KEY=$PHONE_HMAC_KEY

MESSAGING_PROVIDER=console

TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM=
EOF

echo "Wrote $ENV_FILE with generated secrets."
echo "Admin username: owner"
echo "Keep the admin password somewhere safe: it is not stored anywhere by this script."
